frontend/controllers/MyController.php
<?php

namespace frontend\controllers;

use backend\models\Alerts;
use backend\models\Category;
use backend\models\Contacts;
use backend\models\ContactType;
use backend\models\ItemProp;
use backend\models\Items;
use backend\models\ItemStatics;
use backend\models\Privates;
use backend\models\Settings;
use backend\models\Steps;
use common\models\Helper;
use common\models\User;
use frontend\models\Favorites;
use Yii;
use yii\base\InvalidParamException;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use backend\models\Notes;
use backend\models\LabelItems;
use backend\models\Labels;
use lavrentiev\widgets\toastr\Notification;
use yii\imagine\Image;
use Mobizon\MobizonApi;

/**
 * Site controller
 */
class MyController extends Controller
{

    //public $layout='personal';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $model = User::findOne(Yii::$app->user->identity->id);
        if (Yii::$app->request->post()) {
            $model->name = $_POST['User']['name'];
            $model->lastname = $_POST['User']['lastname'];
            $model->middlename = $_POST['User']['middlename'];
            if (Yii::$app->request->post('User')['pass'] != '') {
                if (Yii::$app->request->post('User')['pass'] == Yii::$app->request->post('User')['pass2']) {
                    $model->setPassword(Yii::$app->request->post('User')['pass']);
                    $model->generateAuthKey();
                    Notification::widget([
                        'type' => 'error',
                        'title' => 'Пароль изменен',
                        'message' => 'Вы успешно изменили пароль'
                    ]);
                } else {
                    Notification::widget([
                        'type' => 'error',
                        'title' => 'Пароль не изменен',
                        'message' => 'Введенные пароли не совпадают'
                    ]);
                }
            }
            $model->save();
        }
        return $this->render('index', [
            'model' => $model
        ]);
    }

    public function actionItems()
    {
        $items = Items::find()->where(['user' => Yii::$app->user->identity->id, 'status' => [1, 2, 3, 4, 5]])->all();
        $html = '';
        foreach ($items as $item) {
            $types = ItemProp::findOne(['item_id' => $item['id'], 'row_id' => 1]);
            $types2 = ItemProp::findOne(['item_id' => $item['id'], 'row_id' => 2]);
            $types3 = ItemProp::findOne(['item_id' => $item['id'], 'row_id' => 3]);

            $mask = $types['value'].$types2['value'].$types3['value'];
            $minStep = Steps::findOne(['mask'=>$mask]);

            if ($types['value'] == 1 || $types['value'] == 3) {
                /*** формирование времени подачи объявления ***/
                $date = new \DateTime($item['date_create']);
                $now = new \DateTime();
                $diff = $date->diff($now);
                $item_add_date = '';
                if ($diff->format('%d') > 0) {
                    $item_add_date = 'Добавлено ' . $diff->format('%d') . ' д. назад';
                } else if ($diff->format('%H') > 0) {
                    $item_add_date = 'Добавлено ' . $diff->format('%H') . ' ч. назад';
                } else if ($diff->format('%m') > 0) {
                    $item_add_date = 'Добавлено ' . $diff->format('%m') . ' м. назад';
                } else {
                    $item_add_date = 'Добавлено ' . $diff->format('%s') . ' c. назад';
                }

                /*** Status ***/
                switch ($item['status']) {
                    case '1':
                        $status = '<div>Объявление скоро появится на сайте</div>';
                        break;

                    case '2':
                        $status = '<div class="success"><i class="fa fa-check"></i> Объявление активно и показывается на сайте</div>';
                        break;

                    case '3':
                        $status = '<div class="error"><i class="fa fa-times-circle-o"></i> Модератор отменил публикацию, внесите изменения
</div>';
                        break;

                    case '5':
                        $status = '<div class="error"><i class="fa fa-times-circle-o"></i> Модератор отменил публикацию, требуется ваше внимание
</div>';
                        break;

                    case '4':
                        $status = '<div>Объявление скоро появится на сайте</div>';
                }

                $currency = \frontend\models\Items::getPropLabel($item['id'], '_currency_');
                $iname = Helper::titleFormatItem($item['id']);
                $html .= $this->renderPartial('elements/_item', [
                    'name' => $iname,
                    'img' => Helper::getPicture(\frontend\models\Items::getPropLabel($item['id'], '_photo_'))[0],
                    'date_add' => $item_add_date,
                    'views' => ItemStatics::find()->where(['item_id' => $item['id'], 'type' => 'view'])->count(),
                    'view_phone' => ItemStatics::find()->where(['item_id' => $item['id'], 'type' => 'view-phone'])->count(),
                    'favorite' => Favorites::find()->where(['item_id' => $item['id']])->count(),
                    'hidden' => 0,
                    'price' => $currency == 2 ? \frontend\models\Items::getPropLabel($item['id'], '_price_') * Settings::findOne(1)['value'] . ' usd' : \frontend\models\Items::getPropLabel($item['id'], '_price_') . ' грн',
                    'status' => $status,
                    'st' => $item['status'],
                    'url' => '/catalog/' . \common\models\Helper::str2url($iname) . '-' . $item['id'],
                    'id' => $item['id'],
                    'minStep' => $minStep['id'],
                    'mask' => $mask
                ]);
            }
        }
        $activeMenu = '/my/items';

        return $this->render('items', compact('html', 'activeMenu'));
    }

    public function actionBids()
    {
        $items = Items::find()->where(['user' => Yii::$app->user->identity->id, 'status' => [1, 2, 3, 4, 5]])->all();
        $html = '';
        foreach ($items as $item) {
            $types = ItemProp::findOne(['item_id' => $item['id'], 'row_id' => 1]);
            $types2 = ItemProp::findOne(['item_id' => $item['id'], 'row_id' => 2]);
            $types3 = ItemProp::findOne(['item_id' => $item['id'], 'row_id' => 3]);

            $mask = $types['value'].$types2['value'].$types3['value'];
            $minStep = Steps::findOne(['mask'=>$mask]);
            if ($types['value'] == 2 || $types['value'] == 3) {
                /*** формирование времени подачи объявления ***/
                $date = new \DateTime($item['date_create']);
                $now = new \DateTime();
                $diff = $date->diff($now);
                $item_add_date = '';
                if ($diff->format('%d') > 0) {
                    $item_add_date = 'Добавлено ' . $diff->format('%d') . ' д. назад';
                } else if ($diff->format('%H') > 0) {
                    $item_add_date = 'Добавлено ' . $diff->format('%H') . ' ч. назад';
                } else if ($diff->format('%m') > 0) {
                    $item_add_date = 'Добавлено ' . $diff->format('%m') . ' м. назад';
                } else {
                    $item_add_date = 'Добавлено ' . $diff->format('%s') . ' c. назад';
                }

                /*** Status ***/
                switch ($item['status']) {
                    case '1':
                        $status = '<div>Объявление скоро появится на сайте</div>';
                        break;

                    case '2':
                        $status = '<div class="success"><i class="fa fa-check"></i> Объявление активно и показывается на сайте</div>';
                        break;

                    case '3':
                        $status = '<div class="error"><i class="fa fa-times-circle-o"></i> Модератор отменил публикацию, внесите изменения
</div>';
                        break;

                    case '4':
                        $status = '<div>Объявление скоро появится на сайте</div>';
                }

                $currency = \frontend\models\Items::getPropLabel($item['id'], '_currency_');
                $iname = Helper::titleFormatItem($item['id']);
                $html .= $this->renderPartial('elements/_item', [
                    'name' => $iname,
                    'img' => Helper::getPicture(\frontend\models\Items::getPropLabel($item['id'], '_photo_'))[0],
                    'date_add' => $item_add_date,

frontend/views/my/alerts.php
<?php
$this->params['page'] = '';
$this->title = 'Мои оповещения';

use yii\grid\GridView;
use yii\data\ActiveDataProvider;

\yii\widgets\Pjax::begin(['enablePushState' => false]);
?>

    <div class="dashboard-content dashboard-padding">
        <?php
        $form = \yii\bootstrap\ActiveForm::begin(['options' => ['class' => 'styled-form'], 'fieldConfig' => [
            'options' => [
                'tag' => false,
            ],
        ]]);
        ?>
        <div class="dash-content-limiter">
            <div class="dashboard-page-title">Настройка оповещений</div>
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="styled-input-row">
                        <label class="styled-label">Присылать новости сайта</label>
                        <div class="styled-input-col">
                            <?php
                            $form = \yii\bootstrap\ActiveForm::begin(['options' => ['data-pjax' => true]]);
                            $contacts = \backend\models\Contacts::find()->where(['user' => Yii::$app->user->identity->id])->all();
                            foreach ($contacts as $contact) {
                                if ($contact['type'] == 1) {
                                    $alert = \backend\models\Alerts::find()->where(['user' => Yii::$app->user->identity->id, 'contact_id' => $contact['id'], 'alert_type' => 1])->one();
                                    $checkbox = empty($alert) ? '' : 'checked';
                                    ?>
                                    <div>
                                        <input type="checkbox" <?php echo $checkbox ?>
                                               value="<?php echo $contact['id'] ?>"
                                               name="Email[1][]"> <?php echo $contact['value'] ?>
                                    </div>
                                    <?php
                                } else {
                                    $programs = json_decode($contact['params']);
                                    foreach ($programs as $program) {
                                        $alert = \backend\models\Alerts::find()->where(['user' => Yii::$app->user->identity->id, 'contact_id' => $contact['id'], 'alert_type' => 1, 'chanel'=>$program])->one();
                                        $checkbox = empty($alert) ? '' : 'checked';
                                        ?>
                                        <div>
                                            <input type="checkbox" <?php echo $checkbox ?> value="<?php echo $contact['id'] ?>"
                                                   name="App[1][<?php echo $program ?>][]"> <?php echo $contact['value'] ?>
                                            (<?php echo \backend\models\Contacts::$program[$program] ?>)
                                        </div>
                                        <?php
                                    }
                                }
                            }
                            ?>
                            <button class="btn btn-primary" style="margin-top: 40px;">Сохранить</button>
                            <?php
                            \yii\bootstrap\ActiveForm::end();
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php \yii\bootstrap\ActiveForm::end(); ?>
    </div>
<?php
\yii\widgets\Pjax::end();

frontend/views/my/applications.php
<?php
$this->title = 'Мои заявки';
?>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-3">
            <?=\frontend\components\MyMenuWidget::widget(['active'=>'/my/bids']);?>
        </div>
        <div class="col-md-9">
            <div class="my-box">
                <div class="title">Мои заявки</div>
                <ul class="tabs-ajax clearfix">
                    <li><a href="#">Актуальные</a></li>
                    <li class="active"><a href="#">Ожидающие</a></li>
                    <li><a href="#">Неактуальные</a></li>
                </ul>

                <div class="item-unit">
                    <div class="row clearfix">
                        <div class="col-md-5">
                            <div class="image">
                                <img src="/images/slice-1.png" alt="">
                            </div>
                        </div>
                        <div class="col-md-7 description">
                            <div class="top">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="name">Продам 2х-комнатную квартиру
                                            Ковель, ул. Победы 10</div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="price">780000 грн.</div>
                                    </div>
                                </div>
                            </div>
                            <div class="middle">
                                <div class="success"><i class="fa fa-check"></i> Объявление скоро появится на сайте</div>
                            </div>
                            <div class="bottom">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="add-time">Добавлено: 2 часа назад</div>
                                    </div>
                                    <div class="col-md-6 icon-action">
                                        <a href="#"><i class="fa fa-line-chart"></i></a>
                                        <a href="#"><i class="fa fa-eye"></i></a>
                                        <a href="#"><i class="fa fa-pencil-square-o"></i></a>
                                        <a href="#"><i class="fa fa-arrow-circle-o-up"></i></a>
                                        <a href="#"><i class="fa fa-times"></i></a>
                                        <a href="#"><i class="fa fa-share-square-o"></i></a>
                                    </div>
                                </div>
                                <div class="inform">
                                    <button class="mini-btn"><i class="fa fa-bar-chart"></i></button>
                                    <div>
                                        <i class="fa fa-eye"></i>
                                        Просмотры: 28
                                    </div>
                                    <div>
                                        <i class="fa fa-phone"></i>
                                        Тел: 15
                                    </div>
                                    <div>
                                        <i class="fa fa-heart"></i>
                                        В избранное: 15
                                    </div>
                                    <div>
                                        <i class="fa fa-eye-slash"></i>
                                        Скрыли: 1
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="item-unit">
                    <div class="row clearfix">
                        <div class="col-md-5">
                            <div class="image">
                                <img src="/images/slice-1.png" alt="">
                            </div>
                        </div>
                        <div class="col-md-7 description">
                            <div class="top">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="name">Продам 2х-комнатную квартиру
                                            Ковель, ул. Победы 10</div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="price">780000 грн.</div>
                                    </div>
                                </div>
                            </div>
                            <div class="middle">
                                <div class="error"><i class="fa fa-times-circle"></i> Модератор отменил публикацию, внесите изменения
                                </div>
                            </div>
                            <div class="bottom">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="add-time">Добавлено: 2 часа назад</div>
                                    </div>
                                    <div class="col-md-6 icon-action">
                                        <a href="#"><i class="fa fa-line-chart"></i></a>
                                        <a href="#"><i class="fa fa-eye"></i></a>
                                        <a href="#"><i class="fa fa-pencil-square-o"></i></a>
                                        <a href="#"><i class="fa fa-arrow-circle-o-up"></i></a>
                                        <a href="#"><i class="fa fa-times"></i></a>
                                        <a href="#"><i class="fa fa-share-square-o"></i></a>
                                    </div>
                                </div>
                                <div class="inform">
                                    <button class="mini-btn"><i class="fa fa-bar-chart"></i></button>
                                    <div>
                                        <i class="fa fa-eye"></i>
                                        Просмотры: 28
                                    </div>
                                    <div>
                                        <i class="fa fa-phone"></i>
                                        Тел: 15
                                    </div>
                                    <div>
                                        <i class="fa fa-heart"></i>
                                        В избранное: 15
                                    </div>
                                    <div>
                                        <i class="fa fa-eye-slash"></i>
                                        Скрыли: 1
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/my/favorite.php
<?php
$this->title = 'Избранное';
?>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-3">
            <?=\frontend\components\MyMenuWidget::widget(['active'=>'/my/favorites']);?>
        </div>
        <div class="col-md-9">
            <div class="my-box">
                <div class="title">Избранное</div>

                <?=$html?>
            </div>
        </div>
    </div>
</div>

frontend/views/my/items.php
<?php
$this->title = 'Мои объекты';
?>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-3">
            <?=\frontend\components\MyMenuWidget::widget(['active'=>$activeMenu]);?>
        </div>
        <div class="col-md-9">
            <div class="my-box">
                <div class="title">Мои объекты</div>
                <ul class="tabs-ajax clearfix">
                    <li class="active"><a href="0">Все</a></li>
                    <li><a href="2">Актуальные</a></li>
                    <li><a href="1">На модерации</a></li>
                    <li><a href="3">Не активные</a></li>
                    <li><a href="4">Черновики</a></li>
                    <li><a href="5">Требуют внимания</a></li>
                </ul>

                <?=$html?>
            </div>
        </div>
    </div>
</div>

frontend/views/my/notifications.php
<?php
$this->title = 'Уведомления';
?>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-3">
            <?=\frontend\components\MyMenuWidget::widget(['active'=>'/my/notifications']);?>
        </div>
        <div class="col-md-9">
            <?php
            foreach ($sysNotify as $noty){
                $reads = $noty['read']==''?[]:json_decode($noty['read']);
                if (!in_array(Yii::$app->user->identity->username, $reads)){
                    $reads[] = Yii::$app->user->identity->username;
                    $model = \backend\models\SystemNotifications::findOne($noty['id']);
                    $model->read = json_encode($reads);
                    $model->save();
                }
            ?>
            <div class="notify-box">
                <div class="title"><?=$noty['title']?></div>
                <div class="date"><? $date = new \DateTime($noty['data']); echo $date->format("H:i d.m.Y")?></div>
                <div class="text"><?=$noty['text']?></div>
            </div>
            <?php } ?>
        </div>
    </div>
</div>

frontend/views/my/settings.php
<?php
$this->params['page'] = '';
$this->title = 'Личный кабинет';

use yii\grid\GridView;
use yii\data\ActiveDataProvider;

?>

<div class="dashboard-content dashboard-padding">
    <?php
    $form = \yii\bootstrap\ActiveForm::begin(['options' => ['class' => 'styled-form'], 'fieldConfig' => [
        'options' => [
            'tag' => false,
        ],
    ]]);
    ?>
    <div class="dash-content-limiter">
        <div class="dashboard-page-title">Настройки приватности</div>
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?php
                $form=\yii\bootstrap\ActiveForm::begin();
                $lists = \backend\models\PrivatesList::find()->all();
                foreach ($lists as $list) {
                    $main = \backend\models\Privates::find()->where(['user' => Yii::$app->user->identity->id, 'private_id' => $list['id']])->one();
                    ?>
                    <div class="styled-input-row">
                        <label class="styled-label"><?php echo $list['name'] ?></label>
                        <div class="styled-input-col">
                            <input type="checkbox" value="1" <?php if (!empty($main)) echo 'checked'; ?>
                                   name="Privates[<?php echo $list['id'] ?>]">
                        </div>
                    </div>
                <?php } ?>
                <div class="text-center">
                    <button class="btn btn-primary styled-form-btn">Сохранить</button>
                </div>
                <?php
                \yii\bootstrap\ActiveForm::end();
                ?>
            </div>
        </div>
    </div>

    <?php \yii\bootstrap\ActiveForm::end(); ?>
</div>

frontend/views/my/share.php
<?php
$this->params['page']='';
$this->title='Личный кабинет';
?>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-3">
            <?=\frontend\components\MyMenuWidget::widget(['active'=>'/my/share']);?>
        </div>
        <div class="col-md-9">
            <div class="my-box">
<!--                <div class="title">Пригласить друзей</div>-->
<!--                --><?php
//                \yii\widgets\Pjax::begin(['enablePushState' => false]);
//                $form = \yii\bootstrap\ActiveForm::begin(['action'=>'/my/share-sms', 'options'=>['class'=>'field', 'data-pjax' => true]]);
//                ?>
<!--                <div class="box-group box-group-min row clearfix">-->
<!--                    <div class="col-md-3">-->
<!--                        <div class="label" style="color: black">-->
<!--                            <i class="fa fa-phone"></i>-->
<!--                            Номер телефона:-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="col-md-9">-->
<!--                        <div class="row clearfix">-->
<!--                            <div class="col-md-6">-->
<!--                                <div class="rows-relative"><input type="text" name="phone" value="" required class="form-control"></div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="box-group box-group-min row clearfix">-->
<!--                    <div class="col-md-9 col-md-offset-3">-->
<!--                        <button class="btn btn-success">Пригласить</button>-->
<!--                    </div>-->
<!--                </div>-->
<!--                --><?php
//                \yii\bootstrap\ActiveForm::end();
//                \yii\widgets\Pjax::end();
//                ?>
<!--                <hr/>-->
                <div class="title">Рассказать друзьям</div>
                <script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
                <script src="//yastatic.net/share2/share.js"></script>
                <div class="ya-share2" data-copy="last" data-description="СамСебеРеелтор - поиск и продажа недвижимости без посредников" data-title="СамСебеРеелтор - поиск и продажа недвижимости без посредников" data-url="http://place.w4u.pp.ua/" data-services="vkontakte,facebook,odnoklassniki,twitter,viber,whatsapp,telegram,copy"></div>
            </div>
        </div>
    </div>
</div>

frontend/views/my/sms.php
<?php
$this->title = 'Сообщения';
?>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-3">
            <?=\frontend\components\MyMenuWidget::widget(['active'=>'/my/messages']);?>
        </div>
        <div class="col-md-9 flex-message">
            <div class="my-box border-box">
                <div class="action-top clearfix">
                    <div class="search">
                        <i class="fa fa-search"></i>
                        <input type="text" placeholder="Поиск">
                    </div>
                    <div class="more">
                        <i class="fa fa-ellipsis-h"></i>
                    </div>
                </div>
                <?php
                foreach ($sender as $send){
                    $user = \common\models\User::findOne(['username'=>$send]);
                    $lastMessage = \frontend\models\Messages::find()->where('(from_user=:user_1 and to_user=:user_2) or (from_user=:user_2 and to_user=:user_1)', ['user_1'=>$send, 'user_2'=>Yii::$app->user->identity->username])->orderBy('data DESC')->one();
                    $unread = \frontend\models\Messages::find()->where('from_user=:user_1 and to_user=:user_2 and status=0', ['user_1'=>$send, 'user_2'=>Yii::$app->user->identity->username])->andWhere(['status'=>0])->count();
                ?>
                <div class="one-sms clearfix" data-send="<?=$send?>">
                    <div class="img">
                        <img src="/images/no-photo.jpg" alt="">
                        <span class="online"></span>
                    </div>
                    <div class="text">
                        <div class="name"><?=$user['name']==''?$user['username']:$user['name']?></div>
                        <p><?=$lastMessage['text']?></p>
                    </div>
                    <div class="data">
                        <div class="time"><?=date("H:i", strtotime($lastMessage['data']))?></div>
                        <?php
                        if ($unread>0){
                        ?>
                        <span><?=$unread?></span>
                        <?php } ?>
                    </div>
                </div>
                <?php } ?>
                <div class="one-sms clearfix">
                    <div class="img">
                        <img src="/images/support.png" alt="">
                        <span class="online"></span>
                    </div>
                    <div class="text">
                        <div class="name">Служба поддержки</div>
                    </div>
                    <div class="data">

                    </div>
                </div>
            </div>
            <div class="box-text-message">
                <div class="head">
                    <div class="name">
                        <strong>Марина Кузькина</strong> была в сети сегодня в 20:11
                    </div>
                </div>
                <div class="body" id="list-sms">

                </div>
                <div class="read-box">
                    <a href="#"><i class="fa fa-paperclip"></i></a>
                    <input type="text" name="text" placeholder="Напишите сообщение...">
                    <a href="#" id="send-sms"><i class="fa fa-paper-plane-o"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>